ko:
  languageName: "한국어"
  weight: 1
  title: "김균도 포트폴리오"
  params:
    date_format: "2006-01-02"
    toc_title: "목차"
  menu:
    main:
      - name: "홈"
        url: "/"
        weight: 1
        identifier: home

      - name: "프로젝트"
        url: "/project/"
        weight: 30
        identifier: project

      - name: "자세히"
        url: "/about/"
        weight: 20
        identifier: about

      - name: "블로그"
        url: "https://github.com/kgd3443/kgd3443.github.io"
        weight: 40
        identifier: blog

      - name: "연락처"
        url: "/#contact"
        weight: 90
        identifier: contact

      # 연락처
      - name: "이메일"
        parent: contact
        url: "mailto:shyshy7665@naver.com"
        weight: 91
      - name: "Instagram"
        parent: contact
        url: "https://instagram.com/kim_dog_yun"
        weight: 92
      - name: "이력서 PDF"
        parent: contact
        url: "/uploads/resume.pdf"
        weight: 93
      - name: "메일 보내는 곳"
        parent: contact
        url: "/about/#contact"
        weight: 94

en:
  languageName: "English"
  weight: 2
  title: "Gyundo Kim Portfolio"
  params:
    date_format: "2006-01-02"
    toc_title: "Table of Contents"
  menu:
    main:
      - name: "Home"
        url: "/"
        weight: 1
        identifier: home

      - name: "Projects"
        url: "/project/"
        weight: 30
        identifier: project

      - name: "About"
        url: "/about/"
        weight: 20
        identifier: about

      - name: "Blog"
        url: "https://github.com/kgd3443/kgd3443.github.io"
        weight: 40
        identifier: blog

      - name: "Contact"
        url: "/#contact"
        weight: 90
        identifier: contact

      # Contact submenu
      - name: "Email"
        parent: contact
        url: "mailto:shyshy7665@naver.com"
        weight: 91
      - name: "Instagram"
        parent: contact
        url: "https://instagram.com/kim_dog_yun"
        weight: 92
      - name: "Resume PDF"
        parent: contact
        url: "/uploads/resume.pdf/"
        weight: 93
      - name: "Send Mail"
        parent: contact
        url: "/about/#contact"
        weight: 94
