main:
  - name: Home
    identifier: home
    url: "/"
    weight: 10

  - name: Work
    identifier: work
    url: "/#projects"
    weight: 20

  - name: About
    identifier: about
    url: "/about/"
    weight: 30

  - name: Intro
    parent: home
    url: "/#about"
    weight: 11

  - name: Unity
    parent: work
    url: "https://unity.com/"
    weight: 21

  - name: Web
    parent: work
    url: "/about/"
    weight: 22

  - name: Résumé
    parent: about
    url: "/uploads/resume.pdf"
    weight: 31
